function simple_init
% 
% This document was automatically generated by Code Generator for Scheduling toolbox 
% 

ttInitKernel(1,1,'prioFP');% nbrOfInputs, nbrOfOutputs, fixed priority

data.frequency=48;    %simulation frequency 
data.reg1=0;    % initialization of variable si1
data.reg2=0;    % initialization of variable si2
data.reg3=0;    % initialization of variable si3
data.reg4=0;    % initialization of variable si4
data.reg5=0;    % initialization of variable s1
data.reg6=0;    % initialization of variable s2
data.reg7=0;    % initialization of variable s3
data.reg8=0;    % initialization of variable sd1
data.reg9=0;    % initialization of variable sd2
data.reg10=0;    % initialization of variable sd3
data.reg11=0;    % initialization of variable ke
data.reg12=0;    % initialization of variable u
data.units.unit1= [0,0];    % initialization of unit null
data.units.unit2= [0,0,0,0,0,0,0,0,0,0];    % initialization of unit +
data.units.unit3= [0,0,0];    % initialization of unit *
data.units.unit4= [0,0,0];    % initialization of unit /
data.units.unit5= [0,0];    % initialization of unit ifmin
data.units.unit6= [0,0];    % initialization of unit ifmax
data.units.unit7= [0,0];    % initialization of unit null
data.units.unit8= [0,0];    % initialization of unit zero
data.const1=10;    % initialization of constant K
data.const2=0.85;    % initialization of constant KK
data.const3=0.5;    % initialization of constant T
data.const4=4.25;    % initialization of constant Ti
data.const5=1.24;    % initialization of constant Td
data.const6=10;    % initialization of constant umax
data.const7=-10;    % initialization of constant umin
data.const8=-10;    % initialization of constant smin
data.const9=10;    % initialization of constant smax
data.const10=0.11765;    % initialization of constant c1
data.const11=2.48;    % initialization of constant c2
w=24;
period = w/data.frequency;
deadline = period;
offset = 0;
prio = 1;
ttCreatePeriodictask('task1', offset, period, prio, 'code', data);
